name: command_palette
description: Flutter implementation of a Command Palette. Can be brought up via a keyboard shortcut.
version: 0.7.5
homepage: https://github.com/TNorbury/command_palette
issue_tracker: https://github.com/TNorbury/command_palette/issues
repository: https://github.com/TNorbury/command_palette
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  substring_highlight: ^1.0.33
  woozy_search: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

